# Generated by Django 2.2 on 2019-05-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tasks', models.CharField(max_length=1000)),
                ('due_date', models.DateTimeField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.States')),
            ],
            options={
                'db_table': 'tasklist',
            },
        ),
    ]
