# Generated by Django 2.2 on 2019-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='due_date',
            field=models.DateField(),
        ),
    ]
