# Generated by Django 2.2 on 2019-05-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190506_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='state',
            new_name='task_state',
        ),
    ]
